# -*- coding: utf-8 -*-
"""Contact Book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huft5okYC0XHNLwJlJRV0rOveE4qQsjk
"""

#initializing a empty dictionary to store contacts
contacts={}

#function to add contacts
def add_contact():
    name= input("Enter Name: ").strip()
    ph_no= input("Enter phone Number: ")
    #validation for phone number
    if not ph_no.isdigit():
      print("Enter a Valid Contact Number.")
      return

    #store contact details
    contacts[name]={
        "phone":ph_no
    }
    print("Contact saved successfully.")

#function to view all contacts
def view_contact():
  #checking if contact book is empty
  if not contacts:
    print("No Contact Available!")
  else:
    print("\n---CONTACT LIST---")
    for name,details in contacts.items():
      print("Name: ",name)
      print("Phone: ",contacts[name]["phone"])

#function to Search contacts
def Search_Contact():
  name= input("Enter contact name to search: ")
  #checking if contact exists
  if name in contacts:
    print("Contact Found!")
    print("Name:",name)
    print("phone",contacts[name]["phone"])
  else:
    print("Contact Not Found!")

#function to update contacts
def update_Contact():
  name= input("Enter contact name to Update: ")
  if name in contacts:
    ph_no= input("Enter new phone Number: ")
    #updating dictionary values
    contacts[name]={
          "phone":ph_no
      }
    print("Contact saved successfully.\n")
  else:
    print("Contact Not Found!")

##function to delete contacts
def delete_Contact():
    name= input("Enter contact name to Delete: ")
    if name in contacts:
      contacts.pop(name)
      print(f"{name} deleted successfully!")
    else:
      print("Contact Not Found!\n")

#main program
def menu():
  print("\n CONTACT BOOK APP")
  print("1. Add Contact")
  print("2. View Contacts")
  print("3. Search Contact")
  print("4. Update Contact")
  print("5. Delete Contact")
  print("6. Exit \n")

while True:
    menu()
    choice= int(input("Enter Your choice: "))

    if choice==1:
      add_contact()

    elif choice==2:
      view_contact()

    elif choice==3:
      Search_Contact()

    elif choice==4:
      update_Contact()

    elif choice==5:
      delete_Contact()

    elif choice==6:
      print("Thankyou for using Contact Book App")
      break

    else:
      print("Invalid Choice!Please Try again.")

